github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/txxx-downloader",
  "https://serp.co/products/txxx-downloader/reviews/",
  "https://extensions.serp.co/txxx-downloader",
  "https://browserextensions.io/txxx-downloader"
]
